2019-12-12 16:13:48,613 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-12 16:14:05,431 ERROR: Exception on /edit_profile [POST] [in /Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vish/Projects/flask_tutorial/microblog/app/routes.py", line 84, in edit_profile
    db.session.commit()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/vish/Projects/flask_tutorial/microblog/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'mkldkllkasd', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-12-12 16:21:09,789 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-12 16:21:10,165 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-12 18:39:28,459 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-13 14:56:45,828 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-13 16:20:25,901 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-13 16:20:30,427 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:44:28,783 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:44:45,177 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:44:57,784 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:45:41,293 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:46:12,113 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:46:54,262 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:48:35,094 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:48:50,359 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
2019-12-14 11:56:00,442 INFO: Microblog startup [in /Users/vish/Projects/flask_tutorial/microblog/app/__init__.py:44]
